[package]
name = "logex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log4rs = "1.2.0"
log = { version = "0.4", features = ["std", "serde", "max_level_debug", "release_max_level_warn"] }
